[project]
name = "flaskwiz"
version = "1.0.0"
description = "Allows the creation and storage of enemy stats."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"